# Template for TLS secret (if not using cert-manager)
# To create this secret manually:
# kubectl create secret tls tombalator-tls \
#   --cert=/path/to/cert.pem \
#   --key=/path/to/key.pem \
#   --namespace=tombalator
#
# Or use cert-manager for automatic certificate management
apiVersion: v1
kind: Secret
metadata:
  name: tombalator-tls
  namespace: tombalator
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  # Replace with your actual base64 encoded values
  tls.crt: LS0tLS1CRUdJTi...  # Your certificate
  tls.key: LS0tLS1CRUdJTi...  # Your private key

